/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.primerproyecto.Interfaz;
import java.util.ArrayList;
import com.mycompany.primerproyecto.Funciones.Datos;
import com.mycompany.primerproyecto.Funciones.Funciones;
import javax.swing.ListModel;

/**
 *
 * @author deyla
 */
public class VentanaQuiniela extends javax.swing.JFrame {

    /**
     * Creates new form VentanaQuiniela
     */
    public VentanaQuiniela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGrupos = new javax.swing.JButton();
        btOctavos = new javax.swing.JButton();
        btCuartos = new javax.swing.JButton();
        btSemifinales = new javax.swing.JButton();
        btTercerCuarto = new javax.swing.JButton();
        btFinales = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btGuardar = new javax.swing.JButton();
        lbl_ranking = new javax.swing.JLabel();
        pgb_progreso_mundial = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_ranking = new javax.swing.JList<>();
        btn_actuliza = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        btGrupos.setText("Grupos");
        btGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGruposActionPerformed(evt);
            }
        });

        btOctavos.setText("Octavos");
        btOctavos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOctavosActionPerformed(evt);
            }
        });

        btCuartos.setText("Cuartos");
        btCuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCuartosActionPerformed(evt);
            }
        });

        btSemifinales.setText("Semifinales");
        btSemifinales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSemifinalesActionPerformed(evt);
            }
        });

        btTercerCuarto.setText("Tercero y Cuarto");
        btTercerCuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTercerCuartoActionPerformed(evt);
            }
        });

        btFinales.setText("Finales");
        btFinales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalesActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        lbl_ranking.setText("Ranking");

        pgb_progreso_mundial.setMaximum(64);

        jLabel3.setText("Progreso de Mundial");

        lst_ranking.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lst_ranking);

        btn_actuliza.setText("Actualizar Ranking");
        btn_actuliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actulizaActionPerformed(evt);
            }
        });

        jButton1.setText("Juega Partido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btGuardar)
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btGrupos)
                                    .addComponent(btSemifinales))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(btOctavos)
                                        .addGap(48, 48, 48)
                                        .addComponent(btCuartos))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btTercerCuarto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btFinales))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(lbl_ranking)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2))
                                    .addComponent(btn_actuliza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pgb_progreso_mundial, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jButton1))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btGuardar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ranking)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pgb_progreso_mundial, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_actuliza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btGrupos)
                        .addComponent(btOctavos))
                    .addComponent(btCuartos, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSemifinales)
                    .addComponent(btTercerCuarto)
                    .addComponent(btFinales))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTercerCuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTercerCuartoActionPerformed
        new VentanaTerceroCuarto().setVisible(true);
    }//GEN-LAST:event_btTercerCuartoActionPerformed

    private void btGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGruposActionPerformed
        new VentanaGrupos().setVisible(true); 
    }//GEN-LAST:event_btGruposActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        Funciones.GuardarQuinielas();
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btOctavosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOctavosActionPerformed
        new VentanaOctavos().setVisible(true);
    }//GEN-LAST:event_btOctavosActionPerformed

    private void btCuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCuartosActionPerformed
        new VentanaCuartos().setVisible(true);
    }//GEN-LAST:event_btCuartosActionPerformed

    private void btSemifinalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSemifinalesActionPerformed
        new VentanaSemifinales().setVisible(true);
    }//GEN-LAST:event_btSemifinalesActionPerformed

    private void btFinalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalesActionPerformed
        new VentanaFinal().setVisible(true);
    }//GEN-LAST:event_btFinalesActionPerformed

    private void btn_actulizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actulizaActionPerformed
                      lst_ranking.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = Datos.to_string_nombres_puntos();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }});
        
    }//GEN-LAST:event_btn_actulizaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Datos.partidoActual++;

pgb_progreso_mundial.setValue(Datos.partidoActual);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments});
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaQuiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaQuiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaQuiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaQuiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaQuiniela().setVisible(true);
            }        
        });
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCuartos;
    private javax.swing.JButton btFinales;
    private javax.swing.JButton btGrupos;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btOctavos;
    private javax.swing.JButton btSemifinales;
    private javax.swing.JButton btTercerCuarto;
    private javax.swing.JButton btn_actuliza;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ranking;
    public static javax.swing.JList<String> lst_ranking;
    public static javax.swing.JProgressBar pgb_progreso_mundial;
    // End of variables declaration//GEN-END:variables
}
