/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.primerproyecto.Interfaz;

import com.mycompany.primerproyecto.Funciones.EstructuraPartidos;

/**
 *
 * @author deyla
 */
public class VentanaCuartos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCuartos
     */
    public VentanaCuartos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl21Nov = new javax.swing.JPanel();
        pnlPartido57 = new javax.swing.JPanel();
        lbEscudo2Partido57 = new javax.swing.JLabel();
        lbEscudo1Partido57 = new javax.swing.JLabel();
        btApostarPartido57 = new javax.swing.JButton();
        pnlPartido58 = new javax.swing.JPanel();
        lbEscudo2Partido58 = new javax.swing.JLabel();
        lbEscudo1Partido58 = new javax.swing.JLabel();
        btApostarPartido58 = new javax.swing.JButton();
        pnlPartido59 = new javax.swing.JPanel();
        lbEscudo2Partido59 = new javax.swing.JLabel();
        lbEscudo1Partido59 = new javax.swing.JLabel();
        btApostarPartido59 = new javax.swing.JButton();
        pnlPartido60 = new javax.swing.JPanel();
        lbEscudo2Partido60 = new javax.swing.JLabel();
        lbEscudo1Partido60 = new javax.swing.JLabel();
        btApostarPartido60 = new javax.swing.JButton();

        pnl21Nov.setBackground(new java.awt.Color(0, 102, 0));

        pnlPartido57.setBackground(new java.awt.Color(204, 204, 0));
        pnlPartido57.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 0), new java.awt.Color(204, 204, 0), null, null));
        pnlPartido57.setPreferredSize(new java.awt.Dimension(260, 260));
        pnlPartido57.setRequestFocusEnabled(false);

        lbEscudo2Partido57.setIcon(new javax.swing.ImageIcon("C:\\Users\\deyla\\OneDrive\\Documentos\\escudos\\"+new EstructuraPartidos().infoPartido("Visita","Grupos",56)+".png"));

            lbEscudo1Partido57.setIcon(new javax.swing.ImageIcon("C:\\Users\\deyla\\OneDrive\\Documentos\\escudos\\"+new EstructuraPartidos().infoPartido("Local","Grupos",56)+".png"));

                btApostarPartido57.setBackground(new java.awt.Color(0, 102, 0));
                btApostarPartido57.setText("Apostar");
                btApostarPartido57.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btApostarPartido57ActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout pnlPartido57Layout = new javax.swing.GroupLayout(pnlPartido57);
                pnlPartido57.setLayout(pnlPartido57Layout);
                pnlPartido57Layout.setHorizontalGroup(
                    pnlPartido57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPartido57Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbEscudo1Partido57)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbEscudo2Partido57)
                        .addContainerGap())
                    .addGroup(pnlPartido57Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btApostarPartido57)
                        .addContainerGap(98, Short.MAX_VALUE))
                );
                pnlPartido57Layout.setVerticalGroup(
                    pnlPartido57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPartido57Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlPartido57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEscudo2Partido57)
                            .addComponent(lbEscudo1Partido57))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(btApostarPartido57, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                );

                pnlPartido58.setBackground(new java.awt.Color(204, 204, 0));
                pnlPartido58.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 0), new java.awt.Color(204, 204, 0), null, null));
                pnlPartido58.setPreferredSize(new java.awt.Dimension(260, 260));
                pnlPartido58.setRequestFocusEnabled(false);

                lbEscudo2Partido58.setIcon(new javax.swing.ImageIcon("C:\\Users\\deyla\\OneDrive\\Documentos\\escudos\\"+new EstructuraPartidos().infoPartido("Visita","Grupos",57)+".png"));

                    lbEscudo1Partido58.setIcon(new javax.swing.ImageIcon("C:\\Users\\deyla\\OneDrive\\Documentos\\escudos\\"+new EstructuraPartidos().infoPartido("Local","Grupos",57)+".png"));

                        btApostarPartido58.setBackground(new java.awt.Color(0, 102, 0));
                        btApostarPartido58.setText("Apostar");
                        btApostarPartido58.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btApostarPartido58ActionPerformed(evt);
                            }
                        });

                        javax.swing.GroupLayout pnlPartido58Layout = new javax.swing.GroupLayout(pnlPartido58);
                        pnlPartido58.setLayout(pnlPartido58Layout);
                        pnlPartido58Layout.setHorizontalGroup(
                            pnlPartido58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPartido58Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbEscudo1Partido58)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbEscudo2Partido58)
                                .addContainerGap())
                            .addGroup(pnlPartido58Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(btApostarPartido58)
                                .addContainerGap(98, Short.MAX_VALUE))
                        );
                        pnlPartido58Layout.setVerticalGroup(
                            pnlPartido58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPartido58Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlPartido58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbEscudo2Partido58)
                                    .addComponent(lbEscudo1Partido58))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                                .addComponent(btApostarPartido58, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        );

                        pnlPartido59.setBackground(new java.awt.Color(204, 204, 0));
                        pnlPartido59.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 0), new java.awt.Color(204, 204, 0), null, null));
                        pnlPartido59.setPreferredSize(new java.awt.Dimension(260, 260));
                        pnlPartido59.setRequestFocusEnabled(false);

                        lbEscudo2Partido59.setIcon(new javax.swing.ImageIcon("C:\\Users\\deyla\\OneDrive\\Documentos\\escudos\\"+new EstructuraPartidos().infoPartido("Visita","Grupos",58)+".png"));

                            lbEscudo1Partido59.setIcon(new javax.swing.ImageIcon("C:\\Users\\deyla\\OneDrive\\Documentos\\escudos\\"+new EstructuraPartidos().infoPartido("Local","Grupos",58)+".png"));

                                btApostarPartido59.setBackground(new java.awt.Color(0, 102, 0));
                                btApostarPartido59.setText("Apostar");
                                btApostarPartido59.addActionListener(new java.awt.event.ActionListener() {
                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        btApostarPartido59ActionPerformed(evt);
                                    }
                                });

                                javax.swing.GroupLayout pnlPartido59Layout = new javax.swing.GroupLayout(pnlPartido59);
                                pnlPartido59.setLayout(pnlPartido59Layout);
                                pnlPartido59Layout.setHorizontalGroup(
                                    pnlPartido59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPartido59Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(lbEscudo1Partido59)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbEscudo2Partido59)
                                        .addContainerGap())
                                    .addGroup(pnlPartido59Layout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addComponent(btApostarPartido59)
                                        .addContainerGap(98, Short.MAX_VALUE))
                                );
                                pnlPartido59Layout.setVerticalGroup(
                                    pnlPartido59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPartido59Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(pnlPartido59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lbEscudo2Partido59)
                                            .addComponent(lbEscudo1Partido59))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                                        .addComponent(btApostarPartido59, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                                );

                                pnlPartido60.setBackground(new java.awt.Color(204, 204, 0));
                                pnlPartido60.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 0), new java.awt.Color(204, 204, 0), null, null));
                                pnlPartido60.setPreferredSize(new java.awt.Dimension(260, 260));
                                pnlPartido60.setRequestFocusEnabled(false);

                                lbEscudo2Partido60.setIcon(new javax.swing.ImageIcon("C:\\Users\\deyla\\OneDrive\\Documentos\\escudos\\"+new EstructuraPartidos().infoPartido("Visita","Grupos",59)+".png"));

                                    lbEscudo1Partido60.setIcon(new javax.swing.ImageIcon("C:\\Users\\deyla\\OneDrive\\Documentos\\escudos\\"+new EstructuraPartidos().infoPartido("Local","Grupos",59)+".png"));

                                        btApostarPartido60.setBackground(new java.awt.Color(0, 102, 0));
                                        btApostarPartido60.setText("Apostar");
                                        btApostarPartido60.addActionListener(new java.awt.event.ActionListener() {
                                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                btApostarPartido60ActionPerformed(evt);
                                            }
                                        });

                                        javax.swing.GroupLayout pnlPartido60Layout = new javax.swing.GroupLayout(pnlPartido60);
                                        pnlPartido60.setLayout(pnlPartido60Layout);
                                        pnlPartido60Layout.setHorizontalGroup(
                                            pnlPartido60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlPartido60Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(lbEscudo1Partido60)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbEscudo2Partido60)
                                                .addContainerGap())
                                            .addGroup(pnlPartido60Layout.createSequentialGroup()
                                                .addGap(94, 94, 94)
                                                .addComponent(btApostarPartido60)
                                                .addContainerGap(98, Short.MAX_VALUE))
                                        );
                                        pnlPartido60Layout.setVerticalGroup(
                                            pnlPartido60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlPartido60Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(pnlPartido60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(lbEscudo2Partido60)
                                                    .addComponent(lbEscudo1Partido60))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                                                .addComponent(btApostarPartido60, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())
                                        );

                                        javax.swing.GroupLayout pnl21NovLayout = new javax.swing.GroupLayout(pnl21Nov);
                                        pnl21Nov.setLayout(pnl21NovLayout);
                                        pnl21NovLayout.setHorizontalGroup(
                                            pnl21NovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnl21NovLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(pnl21NovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(pnl21NovLayout.createSequentialGroup()
                                                        .addComponent(pnlPartido57, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(pnlPartido59, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(pnl21NovLayout.createSequentialGroup()
                                                        .addComponent(pnlPartido58, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(pnlPartido60, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        );
                                        pnl21NovLayout.setVerticalGroup(
                                            pnl21NovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnl21NovLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(pnl21NovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(pnlPartido59, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pnlPartido57, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(pnl21NovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(pnlPartido58, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pnlPartido60, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        );

                                        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                                        getContentPane().setLayout(layout);
                                        layout.setHorizontalGroup(
                                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pnl21Nov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        );
                                        layout.setVerticalGroup(
                                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pnl21Nov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        );

                                        pack();
                                    }// </editor-fold>//GEN-END:initComponents

    private void btApostarPartido57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApostarPartido57ActionPerformed
        new VentanaApuesta(56).setVisible(true);
    }//GEN-LAST:event_btApostarPartido57ActionPerformed

    private void btApostarPartido58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApostarPartido58ActionPerformed
        new VentanaApuesta(57).setVisible(true);
    }//GEN-LAST:event_btApostarPartido58ActionPerformed

    private void btApostarPartido59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApostarPartido59ActionPerformed
        new VentanaApuesta(58).setVisible(true);
    }//GEN-LAST:event_btApostarPartido59ActionPerformed

    private void btApostarPartido60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApostarPartido60ActionPerformed
        new VentanaApuesta(69).setVisible(true);
    }//GEN-LAST:event_btApostarPartido60ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCuartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCuartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCuartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCuartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCuartos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btApostarPartido57;
    private javax.swing.JButton btApostarPartido58;
    private javax.swing.JButton btApostarPartido59;
    private javax.swing.JButton btApostarPartido60;
    private javax.swing.JLabel lbEscudo1Partido57;
    private javax.swing.JLabel lbEscudo1Partido58;
    private javax.swing.JLabel lbEscudo1Partido59;
    private javax.swing.JLabel lbEscudo1Partido60;
    private javax.swing.JLabel lbEscudo2Partido57;
    private javax.swing.JLabel lbEscudo2Partido58;
    private javax.swing.JLabel lbEscudo2Partido59;
    private javax.swing.JLabel lbEscudo2Partido60;
    private javax.swing.JPanel pnl21Nov;
    private javax.swing.JPanel pnlPartido57;
    private javax.swing.JPanel pnlPartido58;
    private javax.swing.JPanel pnlPartido59;
    private javax.swing.JPanel pnlPartido60;
    // End of variables declaration//GEN-END:variables
}
