/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.primerproyecto.Interfaz;

import com.mycompany.primerproyecto.Funciones.EstructuraPartidos;

/**
 *
 * @author deyla
 */
public class VentanaTerceroCuarto extends javax.swing.JFrame {

    /**
     * Creates new form VentanaTerceroCuarto
     */
    public VentanaTerceroCuarto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl21Nov = new javax.swing.JPanel();
        pnlPartido63 = new javax.swing.JPanel();
        lbEscudo2Partido63 = new javax.swing.JLabel();
        lbEscudo1Partido63 = new javax.swing.JLabel();
        btApostarPartido63 = new javax.swing.JButton();

        pnl21Nov.setBackground(new java.awt.Color(0, 102, 0));

        pnlPartido63.setBackground(new java.awt.Color(204, 204, 0));
        pnlPartido63.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 0), new java.awt.Color(204, 204, 0), null, null));
        pnlPartido63.setPreferredSize(new java.awt.Dimension(260, 260));
        pnlPartido63.setRequestFocusEnabled(false);

        lbEscudo2Partido63.setIcon(new javax.swing.ImageIcon("C:\\Users\\deyla\\OneDrive\\Documentos\\escudos\\"+new EstructuraPartidos().infoPartido("Visita","Grupos",62)+".png"));

            lbEscudo1Partido63.setIcon(new javax.swing.ImageIcon("C:\\Users\\deyla\\OneDrive\\Documentos\\escudos\\"+new EstructuraPartidos().infoPartido("Local","Grupos",62)+".png"));

                btApostarPartido63.setBackground(new java.awt.Color(0, 102, 0));
                btApostarPartido63.setText("Apostar");
                btApostarPartido63.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btApostarPartido63ActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout pnlPartido63Layout = new javax.swing.GroupLayout(pnlPartido63);
                pnlPartido63.setLayout(pnlPartido63Layout);
                pnlPartido63Layout.setHorizontalGroup(
                    pnlPartido63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPartido63Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbEscudo1Partido63)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbEscudo2Partido63)
                        .addContainerGap())
                    .addGroup(pnlPartido63Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btApostarPartido63)
                        .addContainerGap(98, Short.MAX_VALUE))
                );
                pnlPartido63Layout.setVerticalGroup(
                    pnlPartido63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPartido63Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlPartido63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEscudo2Partido63)
                            .addComponent(lbEscudo1Partido63))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(btApostarPartido63, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                );

                javax.swing.GroupLayout pnl21NovLayout = new javax.swing.GroupLayout(pnl21Nov);
                pnl21Nov.setLayout(pnl21NovLayout);
                pnl21NovLayout.setHorizontalGroup(
                    pnl21NovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl21NovLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlPartido63, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                pnl21NovLayout.setVerticalGroup(
                    pnl21NovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl21NovLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlPartido63, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl21Nov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl21Nov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void btApostarPartido63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApostarPartido63ActionPerformed
        new VentanaApuesta(62).setVisible(true);
    }//GEN-LAST:event_btApostarPartido63ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTerceroCuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTerceroCuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTerceroCuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTerceroCuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTerceroCuarto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btApostarPartido63;
    private javax.swing.JLabel lbEscudo1Partido63;
    private javax.swing.JLabel lbEscudo2Partido63;
    private javax.swing.JPanel pnl21Nov;
    private javax.swing.JPanel pnlPartido63;
    // End of variables declaration//GEN-END:variables
}
