/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.primerproyecto.Interfaz;

import com.mycompany.primerproyecto.Funciones.EstructuraPartidos;

/**
 *
 * @author deyla
 */
public class VentanaSemifinales extends javax.swing.JFrame {

    /**
     * Creates new form VentanaSemifinales
     */
    public VentanaSemifinales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl21Nov = new javax.swing.JPanel();
        pnlPartido61 = new javax.swing.JPanel();
        lbEscudo2Partido61 = new javax.swing.JLabel();
        lbEscudo1Partido61 = new javax.swing.JLabel();
        btApostarPartido61 = new javax.swing.JButton();
        pnlPartido62 = new javax.swing.JPanel();
        lbEscudo2Partido62 = new javax.swing.JLabel();
        lbEscudo1Partido62 = new javax.swing.JLabel();
        btApostarPartido62 = new javax.swing.JButton();

        pnl21Nov.setBackground(new java.awt.Color(0, 102, 0));

        pnlPartido61.setBackground(new java.awt.Color(204, 204, 0));
        pnlPartido61.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 0), new java.awt.Color(204, 204, 0), null, null));
        pnlPartido61.setPreferredSize(new java.awt.Dimension(260, 260));
        pnlPartido61.setRequestFocusEnabled(false);

        lbEscudo2Partido61.setIcon(new javax.swing.ImageIcon("C:\\Users\\deyla\\OneDrive\\Documentos\\escudos\\"+new EstructuraPartidos().infoPartido("Visita","Grupos",60)+".png"));

            lbEscudo1Partido61.setIcon(new javax.swing.ImageIcon("C:\\Users\\deyla\\OneDrive\\Documentos\\escudos\\"+new EstructuraPartidos().infoPartido("Local","Grupos",60)+".png"));

                btApostarPartido61.setBackground(new java.awt.Color(0, 102, 0));
                btApostarPartido61.setText("Apostar");
                btApostarPartido61.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btApostarPartido61ActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout pnlPartido61Layout = new javax.swing.GroupLayout(pnlPartido61);
                pnlPartido61.setLayout(pnlPartido61Layout);
                pnlPartido61Layout.setHorizontalGroup(
                    pnlPartido61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPartido61Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbEscudo1Partido61)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbEscudo2Partido61)
                        .addContainerGap())
                    .addGroup(pnlPartido61Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btApostarPartido61)
                        .addContainerGap(98, Short.MAX_VALUE))
                );
                pnlPartido61Layout.setVerticalGroup(
                    pnlPartido61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPartido61Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlPartido61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEscudo2Partido61)
                            .addComponent(lbEscudo1Partido61))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(btApostarPartido61, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                );

                pnlPartido62.setBackground(new java.awt.Color(204, 204, 0));
                pnlPartido62.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 0), new java.awt.Color(204, 204, 0), null, null));
                pnlPartido62.setPreferredSize(new java.awt.Dimension(260, 260));
                pnlPartido62.setRequestFocusEnabled(false);

                lbEscudo2Partido62.setIcon(new javax.swing.ImageIcon("C:\\Users\\deyla\\OneDrive\\Documentos\\escudos\\"+new EstructuraPartidos().infoPartido("Visita","Grupos",61)+".png"));

                    lbEscudo1Partido62.setIcon(new javax.swing.ImageIcon("C:\\Users\\deyla\\OneDrive\\Documentos\\escudos\\"+new EstructuraPartidos().infoPartido("Local","Grupos",61)+".png"));

                        btApostarPartido62.setBackground(new java.awt.Color(0, 102, 0));
                        btApostarPartido62.setText("Apostar");
                        btApostarPartido62.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btApostarPartido62ActionPerformed(evt);
                            }
                        });

                        javax.swing.GroupLayout pnlPartido62Layout = new javax.swing.GroupLayout(pnlPartido62);
                        pnlPartido62.setLayout(pnlPartido62Layout);
                        pnlPartido62Layout.setHorizontalGroup(
                            pnlPartido62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPartido62Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbEscudo1Partido62)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbEscudo2Partido62)
                                .addContainerGap())
                            .addGroup(pnlPartido62Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(btApostarPartido62)
                                .addContainerGap(98, Short.MAX_VALUE))
                        );
                        pnlPartido62Layout.setVerticalGroup(
                            pnlPartido62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPartido62Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlPartido62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbEscudo2Partido62)
                                    .addComponent(lbEscudo1Partido62))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                                .addComponent(btApostarPartido62, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        );

                        javax.swing.GroupLayout pnl21NovLayout = new javax.swing.GroupLayout(pnl21Nov);
                        pnl21Nov.setLayout(pnl21NovLayout);
                        pnl21NovLayout.setHorizontalGroup(
                            pnl21NovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl21NovLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnl21NovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlPartido62, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlPartido61, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        );
                        pnl21NovLayout.setVerticalGroup(
                            pnl21NovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl21NovLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnlPartido62, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlPartido61, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        );

                        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                        getContentPane().setLayout(layout);
                        layout.setHorizontalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl21Nov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        );
                        layout.setVerticalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl21Nov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        );

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void btApostarPartido62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApostarPartido62ActionPerformed
        new VentanaApuesta(61).setVisible(true);
    }//GEN-LAST:event_btApostarPartido62ActionPerformed

    private void btApostarPartido61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApostarPartido61ActionPerformed
        new VentanaApuesta(60).setVisible(true);
    }//GEN-LAST:event_btApostarPartido61ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSemifinales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSemifinales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSemifinales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSemifinales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSemifinales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btApostarPartido61;
    private javax.swing.JButton btApostarPartido62;
    private javax.swing.JLabel lbEscudo1Partido61;
    private javax.swing.JLabel lbEscudo1Partido62;
    private javax.swing.JLabel lbEscudo2Partido61;
    private javax.swing.JLabel lbEscudo2Partido62;
    private javax.swing.JPanel pnl21Nov;
    private javax.swing.JPanel pnlPartido61;
    private javax.swing.JPanel pnlPartido62;
    // End of variables declaration//GEN-END:variables
}
