/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.primerproyecto.Interfaz;

import com.mycompany.primerproyecto.Funciones.Datos;
import com.mycompany.primerproyecto.Funciones.EstructuraPartidos;
import static com.mycompany.primerproyecto.Funciones.EstructuraPartidos.ganadorApuestaUsuario;
import static com.mycompany.primerproyecto.Funciones.EstructuraPartidos.infoPartido;
import com.mycompany.primerproyecto.Funciones.TreadMundialAutomatico;
import com.mycompany.primerproyecto.Funciones.Usuario;

/**
 *
 * @author deyla
 */
public class VentanaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdmin
     */
    public VentanaAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCargarSiguientePartido = new javax.swing.JButton();
        btReiniciar = new javax.swing.JButton();
        btAutomatico = new javax.swing.JButton();

        btCargarSiguientePartido.setText("Cargar Siguiente partido");
        btCargarSiguientePartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCargarSiguientePartidoActionPerformed(evt);
            }
        });

        btReiniciar.setText("Reiniciar");
        btReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReiniciarActionPerformed(evt);
            }
        });

        btAutomatico.setText("Automatico");
        btAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAutomaticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btReiniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btCargarSiguientePartido)
                .addGap(35, 35, 35)
                .addComponent(btAutomatico)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(474, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCargarSiguientePartido)
                    .addComponent(btReiniciar)
                    .addComponent(btAutomatico))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCargarSiguientePartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCargarSiguientePartidoActionPerformed
        System.out.println("****");
        
        //System.out.println(EstructuraPartidos.infoPartido("MarcadorVisitaReal","Grupos",Datos.partidoActual));
        new VentanaApuesta(Datos.partidoActual).setVisible(true);
    }//GEN-LAST:event_btCargarSiguientePartidoActionPerformed

    private void btReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReiniciarActionPerformed
        EstructuraPartidos.iniciaFaseGrupos();
        Datos.partidoActual = 0;
        for (Object Usuario2 : Datos.getUsuarios()) {
            Usuario usuario= (Usuario)(Usuario2);
            usuario.setPuntos(0);
            
        
         
            
            
        }
    }//GEN-LAST:event_btReiniciarActionPerformed

    private void btAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAutomaticoActionPerformed
        TreadMundialAutomatico tMA = new TreadMundialAutomatico();
        tMA.start();
    }//GEN-LAST:event_btAutomaticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAutomatico;
    private javax.swing.JButton btCargarSiguientePartido;
    private javax.swing.JButton btReiniciar;
    // End of variables declaration//GEN-END:variables
}
